name: Geo Finder Code Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, json, bcmath, curl
        tools: composer, phpunit

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4.1.3

    - name: Deploy to Production
      run: |
        echo "Deploying to production server..."
        ssh root@${{ secrets.SERVER_IP }} "cd /var/www/html/Geo-Finder-Api/ && ./deploy_script.sh"
